apiVersion: v1
kind: Secret
metadata:
  name: general-secret
type: Opaque
data:
  secret-key: TXNQREdwUmhLZDJpT0RHV2daOVlGbkZDZ1ZxTHJIaTU4eWlEeDFNQ3RrTTM1QmpTVkJWQ3VOQTBiMkNhbC1tTHpHWUtVTldHb2hGbXJVRERQYjhPR3c=
