# docker run -it -e ALLOW_PLAINTEXT_LISTENER=yes -e KAFKA_CFG_ZOOKEEPER_CONNECT=192.168.100.6:2181 -e KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://192.168.100.6:9092 -p 9092:9092 bitnami/kafka:3.0.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker0-deployment
spec:
  selector:
    matchLabels:
      app: kafka-broker0
  template:
    metadata:
      labels:
        app: kafka-broker0
    spec:
      containers:
      - name: kafka-broker0
        image: bitnami/kafka:3.0.0
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
        ports:
        - containerPort: 9092
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_CFG_LISTENERS
          value: "PLAINTEXT://:9092"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-broker0-service:9092"
        # - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
        #   value: "PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-broker0-service
spec:
  type: LoadBalancer
  selector:
    app: kafka-broker0
  ports:
  - port: 9092
    targetPort: 9092
    # nodePort: 30092