apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-manager-service-deployment
spec:
  selector:
    matchLabels:
      app: user-manager-service
  template:
    metadata:
      labels:
        app: user-manager-service
    spec:
      containers:
      - name: user-manager-service
        image: rottenbananas.azurecr.io/user-manager-service:release
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: SECRET_KEY
          valueFrom: 
            secretKeyRef:             
              name: general-secret
              key: secret-key
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: user-manager-service
spec:
  type: NodePort
  selector:
    app: user-manager-service
  ports:
  - name: http-port
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30083
