apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-spa-deployment
spec:
  selector:
    matchLabels:
      app: web-spa 
  template:
    metadata:
      labels:
        app: web-spa 
    spec:
      containers:
      - name: web-spa
        image: rottenbananas.azurecr.io/web-spa:release
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: web-spa-service
spec:
  type: NodePort
  selector:
    app: web-spa 
  ports:
  - name: http-port
    port: 80
    targetPort: 80
    nodePort: 30085
