apiVersion: apps/v1
kind: Deployment
metadata:
  name: webspa-envoy-depl
spec:
  selector:
    matchLabels:
      app: webspa-envoy
  template:
    metadata:
      labels:
        app: webspa-envoy
    spec:
      containers:
      - name: webspa-envoy
        image: rottenbananas.azurecr.io/webspa-envoy:release
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: webspa-envoy-service
spec:
  type: LoadBalancer
  selector:
    app: webspa-envoy
  ports:
  - name: http-port
    port: 80
    targetPort: 80
  - name: admin-port
    port: 9901
    targetPort: 9901

