# docker run --rm -p 2181:2181 -it -e ALLOW_ANONYMOUS_LOGIN=yes bitnami/zookeeper:3.6.3

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: my-zookeeper
    # try to put thi label away to see if there is any error
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-zookeeper
  template:
    metadata:
      labels:
        app: my-zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:3.6.3
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
        ports:
        - containerPort: 2181

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  type: ClusterIP
  selector:
    app: my-zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
